---
openapi: "3.0.3"
info:
  title: "LIFEKORA-BLOODBANK"
  description: "REST API endpoints for LIFEKORA-BLOODBANK"
  version: "2026-W06"
servers:
- url: "https"
- url: "http"
tags:
- name: "Demo"
  description: "Demo operations"
paths:
  /demo:
    get:
      tags:
      - "Demo"
      summary: "Fetch all Demos"
      description: "Fetch all Demos"
      operationId: "fetchAllDemo"
      security:
      - oAuth:
        - "demo:read:all"
      parameters:
      - name: "fieldsToExtractCode"
        in: "query"
        required: true
        schema:
          type: "string"
        description: "specify the fields that will be present on the response"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DemoDTO"
    post:
      tags:
      - "Demo"
      summary: "Create a new Demo"
      description: "Create a new Demo"
      operationId: "createDemo"
      security:
      - oAuth:
        - "demo:create"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDemoDTO"
      responses:
        "201":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreationResponseDTO"
  /collector:
    get:
      tags:
      - "Collector"
      summary: "get all Collectors"
      description: "get all Collectors"
      operationId: "getAllCollector"
      security:
      - oAuth:
        - "collector:read:all"
      parameters:
      - name: "page"
        in: "query"
        required: false
        schema:
          type: "integer"
      - name: "limit"
        in: "query"
        required: true
        description: "represents the number of collector to fetch per page."
        schema:
          type: "integer"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectorPaginateDTO"
    post:
      tags:
      - "Collector"
      summary: "Become a collector"
      description: "Become a collector"
      operationId: "becomeCollector"
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCollectorDTO"
      responses:
        "201":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreationResponseDTO"
        "409":
          description: "LIFEKORA_BLOODBANK-409-001 | LIFEKORA_BLOODBANK-409-002 ||\
            \ LIFEKORA_BLOODBANK-409-003"
  /collector/{collectorId}/validate:
    put:
      tags:
      - "Collector"
      summary: "validate a collector"
      description: "validate a collector"
      operationId: "validateCollector"
      security:
      - oAuth:
        - "collector:validate"
      parameters:
      - name: "collectorId"
        in: "path"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "represents the id of collector to validate."
      responses:
        "204":
          description: "successful operation"
        "404":
          description: "LIFEKORA_BLOODBANK-404-003"
  /collector/{collectorId}/reject:
    put:
      tags:
      - "Collector"
      summary: "reject a collector"
      description: "reject a collector"
      operationId: "rejectCollector"
      security:
      - oAuth:
        - "collector:validate"
      parameters:
      - name: "collectorId"
        in: "path"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "represents the id of collector to reject."
      responses:
        "204":
          description: "successful operation"
        "404":
          description: "LIFEKORA_BLOODBANK-404-003"
  /collector/{collectorId}/revoke:
    put:
      tags:
      - "Collector"
      summary: "revoke a collector"
      description: "revoke a collector"
      operationId: "revokeCollector"
      security:
      - oAuth:
        - "collector:validate"
      parameters:
      - name: "collectorId"
        in: "path"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "represents the id of collector to revoke."
      responses:
        "204":
          description: "successful operation"
        "404":
          description: "LIFEKORA_BLOODBANK-404-003"
  /collector/approved:
    get:
      tags:
      - "Collector"
      summary: "get all approved Collectors"
      description: "get all approved Collectors"
      operationId: "getAllApprovedCollector"
      security:
      - bearerAuth: []
      parameters:
      - name: "page"
        in: "query"
        required: false
        schema:
          type: "integer"
      - name: "limit"
        in: "query"
        required: true
        description: "represents the number of approved collector to fetch per page."
        schema:
          type: "integer"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectorPaginateDTO"
  /my/collector/{collectorId}:
    get:
      tags:
      - "Collector"
      summary: "Fetch the user's collector by id of collector"
      description: "Fetch the user's collector by id of collector"
      operationId: "getCollectorById"
      security:
      - bearerAuth: []
      parameters:
      - name: "collectorId"
        in: "path"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "represents the id of collector."
      - name: "fieldsToExtractCode"
        in: "query"
        required: true
        schema:
          type: "string"
        description: "specify the fields that will be present on the response. Supports\
          \ the fieldsToExtractCode1 for the currentUser and fieldsToExtractCode2\
          \ for an appointment"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectorDTO"
        "401":
          description: "LIFEKORA_BLOODBANK-401-001"
        "404":
          description: "LIFEKORA_BLOODBANK-404-003"
    delete:
      tags:
      - "Collector"
      summary: "Delete my collector"
      description: "Delete my collector"
      operationId: "deleteMyCollectorById"
      security:
      - bearerAuth: []
      parameters:
      - name: "collectorId"
        in: "path"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "represents the id of collector."
      responses:
        "204":
          description: "successful operation"
        "401":
          description: "LIFEKORA_BLOODBANK-401-001"
        "404":
          description: "LIFEKORA_BLOODBANK-404-003"
    put:
      tags:
      - "Collector"
      summary: "Edit collector's profile"
      description: "Edit collector's profile"
      operationId: "editCollectorProfile"
      security:
      - bearerAuth: []
      parameters:
      - name: "collectorId"
        in: "path"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "represents the id of collector."
      requestBody:
        required: true
        description: "data needed to edit the new donor"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCollectorDTO"
      responses:
        "204":
          description: "successful operation"
        "404":
          description: "LIFEKORA_BLOODBANK-404-003"
  /collector/{collectorId}:
    get:
      tags:
      - "Collector"
      summary: "Fetch the details collector"
      description: "Fetch the details collector"
      operationId: "getCollectorByIdForAdmin"
      security:
      - oAuth:
        - "collector:read"
      parameters:
      - name: "collectorId"
        in: "path"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "represents the id of collector."
      - name: "fieldsToExtractCode"
        in: "query"
        required: true
        schema:
          type: "string"
        description: "specify the fields that will be present on the response. Supports\
          \ the fieldsToExtractCode1"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectorDTO"
        "404":
          description: "LIFEKORA_BLOODBANK-404-003"
  /demo/{demoId}:
    get:
      tags:
      - "Demo"
      summary: "Fetch demo by id"
      description: "Fetch demo by id"
      operationId: "fetchDemoById"
      security:
      - oAuth:
        - "demo:read"
      parameters:
      - name: "demoId"
        in: "path"
        required: true
        schema:
          type: "string"
          format: "uuid"
        description: "represents the id of demo to fetch."
      - name: "fieldsToExtractCode"
        in: "query"
        required: true
        schema:
          type: "string"
        description: "specify the fields that will be present on the response"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DemoDTO"
        "404":
          description: "SPRING_BOOT_TEMPLATE-404-001"
  /collector/count:
    get:
      tags:
      - "Collector"
      summary: "Get donors count for a given year and the previous year"
      description: "Returns the number of donors in the specified year and the year\
        \ before, to allow year-over-year comparison."
      operationId: "getCollectorsYearOverYearCount"
      security:
      - bearerAuth: []
      parameters:
      - name: "year"
        in: "query"
        required: true
        schema:
          type: "integer"
          format: "int32"
          minimum: "2025"
      responses:
        "200":
          description: "Successful Operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectorStatisticDTO"
components:
  securitySchemes:
    bearerAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
    oAuth:
      type: "oauth2"
      description: "This API uses OAuth 2 with the Authorization Code grant flow."
      flows:
        authorizationCode:
          authorizationUrl: "https://auth.oauth.lao-sarl.cm"
          tokenUrl: "https://token.oauth.lao-sarl.cm"
          scopes:
            demo:read:all: "Needed to fetch all Demo objects"
            demo:create: "Needed when to create a new Demo object"
  schemas:
    DemoDTO:
      type: "object"
      required:
      - "id"
      - "name"
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          type: "string"
    CreateDemoDTO:
      type: "object"
      required:
      - "name"
      properties:
        name:
          type: "string"
    CreationResponseDTO:
      type: "object"
      required:
      - "newId"
      properties:
        newId:
          type: "string"
          format: "uuid"
    CollectorDTO:
      type: "object"
      properties:
        id:
          type: "string"
          description: "the identify of collector"
          format: "uuid"
        authorId:
          type: "string"
          format: "uuid"
        type:
          $ref: "#/components/schemas/CollectorTypeDTO"
        name:
          type: "string"
          description: "the name of collector"
        phoneNumber:
          $ref: "#/components/schemas/PhoneNumberDTO"
        address:
          $ref: "#/components/schemas/AddressDTO"
        email:
          type: "string"
          description: "the email of collector"
        monthlyCollectionCapacity:
          type: "integer"
          description: "monthly collection capacity"
          format: "int64"
        storageCapacity:
          type: "integer"
          description: "storage capacity of collector"
          format: "int64"
        serviceOffered:
          $ref: "#/components/schemas/ServiceOfferedDTO"
        status:
          $ref: "#/components/schemas/StatusDTO"
        documents:
          type: "array"
          description: "the id of official document of collector"
          items:
            type: "string"
            format: "uuid"
            description: "the id of official document of collector"
        createdAt:
          type: "string"
          format: "date-time"
          description: "the date on which he became a collector"
    CollectorTypeDTO:
      enum:
      - "CLINIC"
      - "HOSPITAL"
      - "TRANSFUSION_CENTER"
      - "RESEARCH_INSTITUTE"
    PhoneNumberDTO:
      type: "object"
      properties:
        countryCode:
          type: "string"
          description: "the international code for the country"
          example: "237 for Cameroon"
        number:
          type: "string"
          description: "the phone number"
          example: 653492410
    CreateCollectorDTO:
      type: "object"
      properties:
        type:
          $ref: "#/components/schemas/CollectorTypeDTO"
        name:
          type: "string"
          description: "the official name of collector"
        phoneNumber:
          $ref: "#/components/schemas/PhoneNumberDTO"
        address:
          $ref: "#/components/schemas/AddressDTO"
        email:
          type: "string"
          description: "the email of collector"
        monthlyCollectionCapacity:
          type: "integer"
          description: "monthly collection capacity"
          format: "int64"
        storageCapacity:
          type: "integer"
          description: "storage capacity of collector"
          format: "int64"
        serviceOffered:
          $ref: "#/components/schemas/ServiceOfferedDTO"
        documents:
          type: "array"
          description: "the id of official document of collector"
          items:
            type: "string"
            format: "uuid"
            description: "the id of official document of collector"
    ServiceOfferedDTO:
      enum:
      - "BLOOD_COLLECTION"
      - "PLASMAPHERESIS"
      - "BLOOD_PLATELET_COLLECTION"
      - "BLOOD_TREATMENT"
      - "BIOLOGICAL_TESTS"
      - "DISTRIBUTION_TO_OTHER_ESTABLISHMENTS"
    StatusDTO:
      enum:
      - "APPROVED"
      - "PENDING"
      - "REJECTED"
    AddressDTO:
      type: "object"
      properties:
        city:
          type: "string"
          description: "the city of collector"
        district:
          type: "string"
          description: "the district of collector"
    CollectorStatisticDTO:
      type: "object"
      properties:
        currentYear:
          type: "integer"
          format: "int32"
          example: "2025"
        currentYearCount:
          type: "integer"
          format: "int32"
          example: "150"
        previousYear:
          type: "integer"
          format: "int32"
          example: "2025"
        previousYearCount:
          type: "integer"
          format: "int32"
          example: "120"
    CollectorPaginateDTO:
      type: "object"
      required:
      - "collector"
      - "count"
      - "hasCollector"
      properties:
        collector:
          type: "array"
          items:
            $ref: "#/components/schemas/CollectorDTO"
        count:
          type: "integer"
          format: "int64"
        hasCollector:
          type: "boolean"
    UpdateCollectorDTO:
      type: "object"
      properties:
        type:
          $ref: "#/components/schemas/CollectorTypeDTO"
        name:
          type: "string"
          description: "the official name of collector"
        phoneNumber:
          $ref: "#/components/schemas/PhoneNumberDTO"
        address:
          $ref: "#/components/schemas/AddressDTO"
        email:
          type: "string"
          description: "the email of collector"
        monthlyCollectionCapacity:
          type: "integer"
          description: "monthly collection capacity"
          format: "int64"
        storageCapacity:
          type: "integer"
          description: "storage capacity of collector"
          format: "int64"
        serviceOffered:
          $ref: "#/components/schemas/ServiceOfferedDTO"
